### PR TITLE
Code 8.0.0-alpha.644 changes related to removal of timeout manager.

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Can we wait with this until we have actually branched off for the release-3.0 branch? I'm happy to rebase and reimplement the changes on master once we have bumped master to the next major release

**Comment by bording** [comment]
> Can we wait with this until we have actually branched off for the release-3.0 branch? I'm happy to rebase and reimplement the changes on master once we have bumped master to the next major release

@danielmarbach I don't understand this request. `master` is already using v8 core, so it's already been bumped to 3.0.

**Comment by danielmarbach** [comment]
We have to cherry a bunch of serious changes from master as a new release which will go out as 3.0. Master will become 4.0 at that stage. The gymnastics we are going to do are already complex enough and ASP is definitely the biggest changes we have done as part of the enhancement release. That's why I was asking if we can postpone further merges here. We can easily take the work over so that you can go and finish things up elsewhere.

As already agreed with andreas the v3 will target v7 of core and ship with deprecated timeout storage anyway

**Review by andreasohlund — APPROVED** [review]

**Comment by danielmarbach** [comment]
Superseded by https://github.com/Particular/NServiceBus.Persistence.AzureStorage/pull/330

**Pull request closed without merging**
