### PR TITLE
Update to GitVersion 3.6.3

### PR DESCRIPTION
**Pull request by Scooletz**
Connects to Particular/V6Launch#3

### CODE REVIEW

**Comment by Scooletz** [comment]
Could you take a look @danielmarbach at the `yaml` file in this PR? Considering that we're releasing version 1.0 of this library, is it properly configured?

**Comment by danielmarbach** [comment]
Looks good for me. Have you tested it out locally?

**Comment by Scooletz** [comment]
Not. Doing it right now.

**Comment by Scooletz** [comment]
Checked. It produces right version.
Ping @Particular/azure-storage-persistence-maintainers

**Pull request merged**
