### PR TITLE
Enable non primitive saga's properties

### PR DESCRIPTION
**Pull request by Scooletz**
Solves #7 7

### CODE REVIEW

**Comment by dbelcham** [comment]
@Scooletz is the idea to get this into the package pre-V6 release?

**Comment by Scooletz** [comment]
@dbelcham we can ship it in minor as well. This is not a breaking change. It's an addition.

**Comment by SeanFeldman** [comment]
:+1: any reason why not to have in the v6.0 release? 
Doesn't hold anything back and already available. Brings value to the azure customers.
Potentially would need to be documented.

**Comment by dbelcham** [comment]
Whether to include in this in v6 RC would be something we should probably run by the Plat Dev group. Once RC goes we probably don't want to release until after go-live. Not sure what the current policy/thoughts are on changes like this.

**Comment by Scooletz** [comment]
@dbelcham Could you raise the question in Plat Dev? I think that if you see this as a change that should not be included you're the best person to discuss it. This PR is not urgent and can easily be postponed till the next minor.
@SeanFeldman Thoughts?

**Comment by SeanFeldman** [comment]
As of today, does NHibernate or Raven has the issue of complex types?

If they don't, it feels as if we're getting Azure Storage Persistence on par with the rest of persisters and it would be nice to include it in RC. Otherwise, as a feature unique to a single persistence, I'd raise this with PlatDev.

**Comment by SeanFeldman** [comment]
The sounds like Azure persistence is catching up with the rest :smiley:

**Comment by Scooletz** [comment]
Ping @Particular/azure-storage-persistence-maintainers What do we do with it?

**Comment by yvesgoeleven** [comment]
@Scooletz it's always better to ask for forgiveness then for permission, so let's go for it

**Comment by SimonCropp** [comment]
so does this classify as a critical bug that has to be fixed in the RC?

**Comment by Scooletz** [comment]
@SimonCropp For sure it's not a critical bug. It's an enhancement (fully backward compatible).

**Pull request merged**
