### PR TITLE
Update to latest alpha and fix breaking changes

### PR DESCRIPTION
**Pull request by lailabougria**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Requires a rebase

**Review by ramonsmits — CHANGES_REQUESTED** [review]
All storage related usage of DateTime should remain intact as using DateTimeOffset here could potentially result in deserialization issues and is highly dependant on the storage serializer.

**Comment by danielmarbach** [comment]
Yes DateTimeOffset is highly problematic in ASP. That being said we are dropping support for the timeout storage in #308. Maybe this PR can be based on top of that one?

**Comment by danielmarbach** [comment]
Rebased for you

**Review by danielmarbach — APPROVED** [review]

**Comment by lailabougria** [comment]
@ramonsmits: What Daniel said 😬 
@danielmarbach: We can't because the TF still hasn't got there and we're trying to wrap this work up

**Review by ramonsmits — APPROVED** [review]

**Pull request merged**
