### PR TITLE
Consolidate table creation

### PR DESCRIPTION
**Pull request by danielmarbach**
When the installers are enabled and no opt-out from table creation is present the default table will be created in the installer and the saga persister will create tables at runtime if necessary.

### CODE REVIEW

**Comment by danielmarbach** [comment]
We still have the saga and subscription storage-specific  `CreateSchema` under 

```
WellKnownConfigurationKeys.SagaStorageCreateSchema
WellKnownConfigurationKeys.SubscriptionStorageCreateSchema
```

So at this stage, the saga persister would still create the saga tables dynamically unless you opt out by calling `sagaPersistence.CreateSchema(false)`.

**Comment by lailabougria** [comment]
> I guess another option would be to call it DisableTableCreation and then if you call it no table will ever be created. I think I actually prefer that

👍  to that!

**Comment by danielmarbach** [comment]
@lailabougria what would your expectation be if you call

`DisableTableCreation` but `CreateSchema(true)` on the saga persistence?

**Comment by lailabougria** [comment]
image

**Review by lailabougria — APPROVED** [review]

**Pull request merged**
