### PR TITLE
Prepare for final beta release

### PR DESCRIPTION
**Pull request by bording**

### CODE REVIEW

**Comment by bording** [comment]
@Particular/azure-maintainers It looks like there are test failures, some of which would be related to moving to the latest core beta I suspect.

**Comment by SeanFeldman** [comment]
@bording looking at the tests, something with native delayed delivery rather than Core beta.  I suspect it's a bug introduced lately. Let me verify.

**Comment by bording** [comment]
@SeanFeldman You're right. I accidentally looked at the failures on the latest develop test run earlier.

**Comment by SeanFeldman** [comment]
@bording sorry for this regression. We'll address it ASAP as it's also a patch for deployed `master`.
Could you confirm that once this hotfix is ported back to ASQ `develop`, `release` branch would need to be re-worked?

**Comment by bording** [comment]
Just pushed up a change to update to NServiceBus.Azure.Transports.WindowsAzureStorageQueues 8.0.0-beta0008, so lets see those tests pass now!

**Comment by SeanFeldman** [comment]
🤞

**Pull request merged**
